package i5.las2peer.services.mensa;


import java.net.HttpURLConnection;

import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.Consumes;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.MediaType;

import i5.las2peer.api.Context;
import i5.las2peer.api.ManualDeployment;
import i5.las2peer.api.ServiceException;
import i5.las2peer.api.logging.MonitoringEvent;
import i5.las2peer.restMapper.RESTService;
import i5.las2peer.restMapper.annotations.ServicePath;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Contact;
import io.swagger.annotations.Info;
import io.swagger.annotations.License;
import io.swagger.annotations.SwaggerDefinition;
import org.json.simple.*;

import javax.annotation.security.RolesAllowed;
import org.glassfish.jersey.server.filter.RolesAllowedDynamicFeature;


import java.util.HashMap;
import java.util.Map;
 

/**
 *
 * 302
 *
 * This microservice was generated by the CAE (Community Application Editor). If you edit it, please
 * make sure to keep the general structure of the file and only add the body of the methods provided
 * in this main file. Private methods are also allowed, but any "deeper" functionality should be
 * outsourced to (imported) classes.
 *
 */
@ServicePath("mensa")
@ManualDeployment
public class Mensa extends RESTService {





  public Mensa() {
	super();
    // read and set properties values
    setFieldValues();
    
  }

  @Override
  public void initResources() {
	getResourceConfig().register(RootResource.class);
	getResourceConfig().register(RolesAllowedDynamicFeature.class);
  }

  // //////////////////////////////////////////////////////////////////////////////////////
  // REST methods
  // //////////////////////////////////////////////////////////////////////////////////////

  @Api
  @SwaggerDefinition(
      info = @Info(title = "302", version = "0.0.0",
          description = "",
          termsOfService = "",
          contact = @Contact(name = "", email = "CAEAddress@gmail.com") ,
          license = @License(name = "BSD",
              url = "https://github.com/PhilCAEOrg2/microservice-302/blob/master/LICENSE.txt") ) )
  @Path("/")
  public static class RootResource {

    private final Mensa service = (Mensa) Context.getCurrent().getService();

      /**
   * 
   * postDish
   *
   * 
   * @param body  a JSONObject
   * 
   * @return Response 
   * 
   */
  @POST
  @Path("/dishes")
  @Produces(MediaType.APPLICATION_JSON)
  @Consumes(MediaType.APPLICATION_JSON)
  
  @ApiResponses(value = {
       @ApiResponse(code = HttpURLConnection.HTTP_BAD_REQUEST, message = "badreq"),
       @ApiResponse(code = HttpURLConnection.HTTP_CREATED, message = "createdDish")
  })
  @ApiOperation(value = "postDish", notes = " ")
  public Response postDish(String body) {
   classes.Dish payloadbodyObject = new classes().new Dish();
   try { 
       payloadbodyObject.fromJSON(body);
   } catch (Exception e) { 
       e.printStackTrace();
       JSONObject result = new JSONObject();
       return Response.status(HttpURLConnection.HTTP_INTERNAL_ERROR).entity("Cannot convert json to object").build();
   }



     
    // service method invocations

     




    // badreq
    boolean badreq_condition = true;
    if(badreq_condition) {
      JSONObject badreq = new JSONObject();

      

      return Response.status(HttpURLConnection.HTTP_BAD_REQUEST).entity(badreq.toJSONString()).build();
    }
    // createdDish
    boolean createdDish_condition = true;
    if(createdDish_condition) {
      JSONObject createdDish = new JSONObject();

      

      return Response.status(HttpURLConnection.HTTP_CREATED).entity(createdDish.toJSONString()).build();
    }
    return null;
  }

  /**
   * 
   * getDishById
   *
   * 
   * @param id  a String
   * 
   * @return Response 
   * 
   */
  @GET
  @Path("/dishes/{id}")
  @Produces(MediaType.APPLICATION_JSON)
  @Consumes(MediaType.TEXT_PLAIN)
  
  @ApiResponses(value = {
       @ApiResponse(code = HttpURLConnection.HTTP_OK, message = "ok"),
       @ApiResponse(code = HttpURLConnection.HTTP_NOT_FOUND, message = "nf")
  })
  @ApiOperation(value = "getDishById", notes = " ")
  public Response getDishById(@PathParam("id") String id) {




     
    // service method invocations

     




    // ok
    boolean ok_condition = true;
    if(ok_condition) {
      JSONObject ok = new JSONObject();

      

      return Response.status(HttpURLConnection.HTTP_OK).entity(ok.toJSONString()).build();
    }
    // nf
    boolean nf_condition = true;
    if(nf_condition) {
      JSONObject nf = new JSONObject();

      

      return Response.status(HttpURLConnection.HTTP_NOT_FOUND).entity(nf.toJSONString()).build();
    }
    return null;
  }

  /**
   * 
   * getDishes
   *
   * 
   *
   * 
   * @return Response 
   * 
   */
  @GET
  @Path("/dishes")
  @Produces(MediaType.APPLICATION_JSON)
  @Consumes(MediaType.TEXT_PLAIN)
  
  @ApiResponses(value = {
       @ApiResponse(code = HttpURLConnection.HTTP_OK, message = "dishes")
  })
  @ApiOperation(value = "getDishes", notes = " ")
  public Response getDishes() {




     
    // service method invocations

     




    // dishes
    boolean dishes_condition = true;
    if(dishes_condition) {
      JSONObject dishes = new JSONObject();

      

      return Response.status(HttpURLConnection.HTTP_OK).entity(dishes.toJSONString()).build();
    }
    return null;
  }

  /**
   * 
   * postRating
   *
   * 
   * @param id  a String
   * 
   * @return Response 
   * 
   */
  @POST
  @Path("/dishes/{id}/rating")
  @Produces(MediaType.APPLICATION_JSON)
  @Consumes(MediaType.TEXT_PLAIN)
  
  @ApiResponses(value = {
       @ApiResponse(code = HttpURLConnection.HTTP_UNAUTHORIZED, message = "unauth"),
       @ApiResponse(code = HttpURLConnection.HTTP_CREATED, message = "ok")
  })
  @ApiOperation(value = "postRating", notes = " ")
  public Response postRating(@PathParam("id") String id) {




     
    // service method invocations

     




    // unauth
    boolean unauth_condition = true;
    if(unauth_condition) {
      JSONObject unauth = new JSONObject();

      

      return Response.status(HttpURLConnection.HTTP_UNAUTHORIZED).entity(unauth.toJSONString()).build();
    }
    // ok
    boolean ok_condition = true;
    if(ok_condition) {
      JSONObject ok = new JSONObject();

      

      return Response.status(HttpURLConnection.HTTP_CREATED).entity(ok.toJSONString()).build();
    }
    return null;
  }



  }

  // //////////////////////////////////////////////////////////////////////////////////////
  // Service methods (for inter service calls)
  // //////////////////////////////////////////////////////////////////////////////////////
  
  

  // //////////////////////////////////////////////////////////////////////////////////////
  // Custom monitoring message descriptions (can be called via RMI)
  // //////////////////////////////////////////////////////////////////////////////////////

  public Map<String, String> getCustomMessageDescriptions() {
    Map<String, String> descriptions = new HashMap<>();
    
    return descriptions;
  }

}
